# Generated by Django 6.0 on 2026-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
                ('total_transactions', models.IntegerField(default=0)),
                ('bank_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
