# Generated by Django 6.0 on 2026-01-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationrecord",
            name="client_name",
            field=models.CharField(default="client", max_length=255),
        ),
    ]
